# Complete pandas Cheatsheet Notebook With Examples !

In [1]:
import pandas as pd
import numpy as np

# read_csv() function:

# parameters of read_csv file:

**1. path of the file**

**2.sep=',' :-** the sep parameter is delimeter which is used different in different files by default comma for csv files
( if u are using any other file type the u have to specify delimeter in sep parameter.

**3.Index_col='any colm of data' :-** if u want to specify any colum of data set as index then u will give that colum here.

**4.usecols=['colm1','colm2',...,'colmN'] :-** it is used when u do not want all the colms of data set u only want specific colms then u can 
select those specific colms by giving their values in this parameter.

**5.Skiprows/nrows =number :-**  if u want to skip some rows while loading or want a specific number of rows then this is used.

**6.Encoding :-** this parameter is used when your data has a different encoding by dafult is latin-1.

**7.Skip_bad_lines=false :-**

**8.dtypes={'colm1':datatype,'colm2':datatype,...} :-**  this is used when u want to change the data type of a specific colum 
 at the start while loading dataset
 
**9.parse_dates=['colum1','colm2'] :-** this is uesd when your data has date column but their datatype is string or other then u can change their 
datatype by using this parameter while loading dataset.

**10.Chunksize=nummer :-** if your data file is very large then it will take so much time to load ,so u can use this parameter to load data 
in chunks or parts.

# Series 
**Series**:- A pandas series is like a column in a table it is a 1D array holding data of a perticuler datatype.

### How to make series:

In [144]:

marks=[33,54,65,23,55,75]
sub=['physis','Math','sindhi','urdu','English','bio']
Result=pd.Series(marks,index=sub,name='Result')
Result

physis     33
Math       54
sindhi     65
urdu       23
English    55
bio        75
Name: Result, dtype: int64

# Functions of Series:

In [145]:
# size : it is used to check the size of colum
Result.size

6

In [146]:
# dtype: It is used to check the datatype of Series
Result.dtype

dtype('int64')

In [147]:
# is_unique: it is used to check either the series contain duplicates or the series is completly unique
Result.is_unique

True

In [148]:
# index : it gives the index of a Series
Result.index

Index(['physis', 'Math', 'sindhi', 'urdu', 'English', 'bio'], dtype='object')

In [149]:
# sort_values: it sorts the series in ascending or descending order
Result.sort_values(ascending=False)

bio        75
sindhi     65
English    55
Math       54
physis     33
urdu       23
Name: Result, dtype: int64

In [150]:
# sort_index : it sorts the index of a Series
Result.sort_index(ascending=False)

urdu       23
sindhi     65
physis     33
bio        75
Math       54
English    55
Name: Result, dtype: int64

In [151]:
# value_counts : it counts the frequency or mode of a value in series or dataframe
Result.value_counts()

Result
33    1
54    1
65    1
23    1
55    1
75    1
Name: count, dtype: int64

In [152]:
#count : it counts the number of values in a series
Result.count()

np.int64(6)

In [153]:
# sum : it find the total of a series or add the values of a series
Result.sum()

np.int64(305)

# Indexing of Series

In [154]:
# fetching a value through label
Result.iloc[0]

np.int64(33)

In [155]:
# fetching values through label
Result.loc['bio']

np.int64(75)

In [156]:
# fetching series of values in  specfied range
Result.iloc[0:3]

physis    33
Math      54
sindhi    65
Name: Result, dtype: int64

In [157]:
# fetchi
Result.loc['urdu':'bio']

urdu       23
English    55
bio        75
Name: Result, dtype: int64

# Satistical function

In [158]:
# mean :  finds the mean of series
Result.mean()

np.float64(50.833333333333336)

In [159]:
# median : finds the median of series
Result.median()

54.5

In [160]:
# mode  : finds the mode of series
Result.mode()

0    23
1    33
2    54
3    55
4    65
5    75
Name: Result, dtype: int64

In [161]:
# std : find te standard deviation of series
Result.std()

19.518367418067186

# Series with pthon functions

In [162]:
# len : finds the length of a series
len(Result)

6

In [163]:
# type : finds the object type of a series or df
type(Result)

pandas.core.series.Series

In [164]:
# sorted : it sorts a values and creates a copy
sorted(Result)

[23, 33, 54, 55, 65, 75]

In [165]:
# min / max : finds the min and max value of series
min(Result)
max(Result)

75

In [166]:
# membership operator
8 in Result

False

#  Some important functions

In [167]:
# astype : changes the type of a Series
Result.astype('string')

physis     33
Math       54
sindhi     65
urdu       23
English    55
bio        75
Name: Result, dtype: string

In [168]:
# between : finds the values between a given range 
Result.between(40,70)

physis     False
Math        True
sindhi      True
urdu       False
English     True
bio        False
Name: Result, dtype: bool

In [169]:
# clip : it transforms the values of a series in a perticuler range , large values will be equal to max and small value equal to min
Result.clip(30,70)

physis     33
Math       54
sindhi     65
urdu       30
English    55
bio        70
Name: Result, dtype: int64

In [170]:
# drop_duplicates() : it drop all the duplicated values of a series
Result.drop_duplicates()

physis     33
Math       54
sindhi     65
urdu       23
English    55
bio        75
Name: Result, dtype: int64

In [171]:
# duplicated : it finds either the series has duplicate values or not
Result.duplicated()

physis     False
Math       False
sindhi     False
urdu       False
English    False
bio        False
Name: Result, dtype: bool

In [172]:
# isnull : is find does a series has any null value
Result.isnull

<bound method Series.isnull of physis     33
Math       54
sindhi     65
urdu       23
English    55
bio        75
Name: Result, dtype: int64>

In [173]:
#dropna : it removes all na values from series
Result.dropna

<bound method Series.dropna of physis     33
Math       54
sindhi     65
urdu       23
English    55
bio        75
Name: Result, dtype: int64>

In [174]:
# fillna : it fill na values with given vlaue
Result.fillna(4) # fill na with 4

physis     33
Math       54
sindhi     65
urdu       23
English    55
bio        75
Name: Result, dtype: int64

In [175]:
# isin : it chacks either ther the values is present in series
Result.isin([33,55])
# apply : it apply a user defined function on series
# copy : it creates a copy of a series and stores in a variable

physis      True
Math       False
sindhi     False
urdu       False
English     True
bio        False
Name: Result, dtype: bool

# Dataframe in pandas
**Defination**: Dataframe is combination of series of a data fram or more than one series commbine to gether to form dataframe

In [176]:
# creatation of datafram
data={'Hunter_id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
'Hunter_name':['Ram','Sham','Jam','Ali','Ahsan','Ahmed','Mustafa','Sita','Arslan',np.nan,'Ram','Nawaz','Akber','Hasan','Rohid'],
    'Hunted_animal':['Cow','Lion','cow','buffalo','Bird','Elefent','cow','Geraf',np.nan,'Gerof','Tiger','Got','Duck','Failed','Fox'],
    'Animal_weight':[250,2000,400,230,10,5990,290,8700,np.nan,np.nan,5550,150,20,0,15]}
df=pd.DataFrame(data)
df

    Hunter_id Hunter_name Hunted_animal  Animal_weight
0           1         Ram           Cow          250.0
1           2        Sham          Lion         2000.0
2           3         Jam           cow          400.0
3           4         Ali       buffalo          230.0
4           5       Ahsan          Bird           10.0
5           6       Ahmed       Elefent         5990.0
6           7     Mustafa           cow          290.0
7           8        Sita         Geraf         8700.0
8           9      Arslan           NaN            NaN
9          10         NaN         Gerof            NaN
10         11         Ram         Tiger         5550.0
11         12       Nawaz           Got          150.0
12         13       Akber          Duck           20.0
13         14       Hasan        Failed            0.0
14         15       Rohid           Fox           15.0

# Fnctions of dataframe

In [177]:
# shape : IT is used to find the shape of the data frame
df.shape

(15, 4)

In [178]:
# dtypes : It is used to find the data type of each column of dataframe
df.dtypes

Hunter_id          int64
Hunter_name       object
Hunted_animal     object
Animal_weight    float64
dtype: object

In [179]:
# head(),tail(),sample(): these are used to show the rows of dataframe .
df.head() # show first 5 rows
df.tail() # shows Last 5 rows
df.sample() # shows random any row from data

   Hunter_id Hunter_name Hunted_animal  Animal_weight
8          9      Arslan           NaN            NaN

In [180]:
#index: It will show the index of the data fram
df.index

RangeIndex(start=0, stop=15, step=1)

In [181]:
# columns : It will show the columns of dataset
df.columns

Index(['Hunter_id', 'Hunter_name', 'Hunted_animal', 'Animal_weight'], dtype='object')

# Important Functions

In [182]:
# info() function : it is used to show a quick reviwe of data with its No of columns and their data types and No of rows
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Hunter_id      15 non-null     int64
 1   Hunter_name    14 non-null     object
 2   Hunted_animal  14 non-null     object
 3   Animal_weight  13 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 612.0+ bytes

In [183]:
# describe() : it is used for quicke statistical overview
df.describe()

       Hunter_id  Animal_weight
count  15.000000      13.000000
mean    8.000000    1815.769231
std     4.472136    2942.420946
min     1.000000       0.000000
25%     4.500000      20.000000
50%     8.000000     250.000000
75%    11.500000    2000.000000
max    15.000000    8700.000000

In [184]:
# duplicated : it is used to show the duplicated observations in dataset
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

# Mathematical functions

In [185]:
# .sum() : it is used to add values of a numeric colum
df['Animal_weight'].sum()

np.float64(23605.0)

In [186]:
# min / max : finds the min and max value of series
df['Animal_weight'].min()

0.0

In [187]:
df['Animal_weight'].max()

8700.0

In [188]:
#  mean : It shows the average of a numeric column
df['Animal_weight'].mean()

np.float64(1815.7692307692307)

# Indexing of DataFrame

In [189]:
# fetching one values using index
df['Animal_weight'].iloc[0] # u can do like Result[0]

np.float64(250.0)

In [190]:
# fetching one value using label index
df['Animal_weight'].loc[3] # here 3 is index which are considered as label here

np.float64(230.0)

In [191]:
# fetching rang of values  using index
df['Animal_weight'].iloc[1:3]

1    2000.0
2     400.0
Name: Animal_weight, dtype: float64

In [192]:
# fetching rang of values  using Label
df['Animal_weight'].loc[3:6] # here 3 and 6 are index which are considered as label here

3     230.0
4      10.0
5    5990.0
6     290.0
Name: Animal_weight, dtype: float64

# Creating New columns

In [193]:
# syntax : df['coulumn_name']=values 
df['Hunter_status']=['Middleclass','Rich','Poor','MiddleClass','Poor','Rich','MidleClass','Rich','Poor','Rich','Poor','Rich','Middleclass','Poor','Rich']
df

    Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
0           1         Ram           Cow          250.0   Middleclass
1           2        Sham          Lion         2000.0          Rich
2           3         Jam           cow          400.0          Poor
3           4         Ali       buffalo          230.0   MiddleClass
4           5       Ahsan          Bird           10.0          Poor
5           6       Ahmed       Elefent         5990.0          Rich
6           7     Mustafa           cow          290.0    MidleClass
7           8        Sita         Geraf         8700.0          Rich
8           9      Arslan           NaN            NaN          Poor
9          10         NaN         Gerof            NaN          Rich
10         11         Ram         Tiger         5550.0          Poor
11         12       Nawaz           Got          150.0          Rich
12         13       Akber          Duck           20.0   Middleclass
13         14       Hasan        Failed            0.0          Poor
14         15       Rohid           Fox           15.0          Rich

# Drop a column

In [194]:
df.drop(columns=['Hunter_name'])

    Hunter_id Hunted_animal  Animal_weight Hunter_status
0           1           Cow          250.0   Middleclass
1           2          Lion         2000.0          Rich
2           3           cow          400.0          Poor
3           4       buffalo          230.0   MiddleClass
4           5          Bird           10.0          Poor
5           6       Elefent         5990.0          Rich
6           7           cow          290.0    MidleClass
7           8         Geraf         8700.0          Rich
8           9           NaN            NaN          Poor
9          10         Gerof            NaN          Rich
10         11         Tiger         5550.0          Poor
11         12           Got          150.0          Rich
12         13          Duck           20.0   Middleclass
13         14        Failed            0.0          Poor
14         15           Fox           15.0          Rich

# Most important functions of dataframe

In [195]:
# astype : changes the type of a dataframe
df['Animal_weight'].astype('string')

0      250.0
1     2000.0
2      400.0
3      230.0
4       10.0
5     5990.0
6      290.0
7     8700.0
8       <NA>
9       <NA>
10    5550.0
11     150.0
12      20.0
13       0.0
14      15.0
Name: Animal_weight, dtype: string

In [196]:
# drop_duplicates() : it drop all the duplicated values of a dataframe
df.drop_duplicates()

    Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
0           1         Ram           Cow          250.0   Middleclass
1           2        Sham          Lion         2000.0          Rich
2           3         Jam           cow          400.0          Poor
3           4         Ali       buffalo          230.0   MiddleClass
4           5       Ahsan          Bird           10.0          Poor
5           6       Ahmed       Elefent         5990.0          Rich
6           7     Mustafa           cow          290.0    MidleClass
7           8        Sita         Geraf         8700.0          Rich
8           9      Arslan           NaN            NaN          Poor
9          10         NaN         Gerof            NaN          Rich
10         11         Ram         Tiger         5550.0          Poor
11         12       Nawaz           Got          150.0          Rich
12         13       Akber          Duck           20.0   Middleclass
13         14       Hasan        Failed            0.0          Poor
14         15       Rohid           Fox           15.0          Rich

In [197]:
# duplicated : it finds either the series has duplicate values or not
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [198]:
# isnull : is find does a dataframe has any null value
df.isnull

<bound method DataFrame.isnull of     Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
0           1         Ram           Cow          250.0   Middleclass
1           2        Sham          Lion         2000.0          Rich
2           3         Jam           cow          400.0          Poor
3           4         Ali       buffalo          230.0   MiddleClass
4           5       Ahsan          Bird           10.0          Poor
5           6       Ahmed       Elefent         5990.0          Rich
6           7     Mustafa           cow          290.0    MidleClass
7           8        Sita         Geraf         8700.0          Rich
8           9      Arslan           NaN            NaN          Poor
9          10         NaN         Gerof            NaN          Rich
10         11         Ram         Tiger         5550.0          Poor
11         12       Nawaz           Got          150.0          Rich
12         13       Akber          Duck           20.0   Middleclass
13         14       Hasan        Failed            0.0          Poor
14         15       Rohid           Fox           15.0          Rich>

In [199]:
# value_counts() : it counts the frequency of a values in a dataframe
df['Hunted_animal'].value_counts()

Hunted_animal
cow        2
Cow        1
Lion       1
buffalo    1
Bird       1
Elefent    1
Geraf      1
Gerof      1
Tiger      1
Got        1
Duck       1
Failed     1
Fox        1
Name: count, dtype: int64

In [200]:
# sort_values() : it sorts columns of a data frame in Asscending or decending order
df['Hunted_animal'].sort_values() # sort the values of one column separatly
df.sort_values('Hunter_name') # sort the column in whole data frame

    Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
5           6       Ahmed       Elefent         5990.0          Rich
4           5       Ahsan          Bird           10.0          Poor
12         13       Akber          Duck           20.0   Middleclass
3           4         Ali       buffalo          230.0   MiddleClass
8           9      Arslan           NaN            NaN          Poor
13         14       Hasan        Failed            0.0          Poor
2           3         Jam           cow          400.0          Poor
6           7     Mustafa           cow          290.0    MidleClass
11         12       Nawaz           Got          150.0          Rich
0           1         Ram           Cow          250.0   Middleclass
10         11         Ram         Tiger         5550.0          Poor
14         15       Rohid           Fox           15.0          Rich
1           2        Sham          Lion         2000.0          Rich
7           8        Sita         Geraf         8700.0          Rich
9          10         NaN         Gerof            NaN          Rich

In [201]:
# set_index() : it is used to set a column as index of dataframe
data=df.set_index('Hunter_name')
data

             Hunter_id Hunted_animal  Animal_weight Hunter_status
Hunter_name
Ram                  1           Cow          250.0   Middleclass
Sham                 2          Lion         2000.0          Rich
Jam                  3           cow          400.0          Poor
Ali                  4       buffalo          230.0   MiddleClass
Ahsan                5          Bird           10.0          Poor
Ahmed                6       Elefent         5990.0          Rich
Mustafa              7           cow          290.0    MidleClass
Sita                 8         Geraf         8700.0          Rich
Arslan               9           NaN            NaN          Poor
NaN                 10         Gerof            NaN          Rich
Ram                 11         Tiger         5550.0          Poor
Nawaz               12           Got          150.0          Rich
Akber               13          Duck           20.0   Middleclass
Hasan               14        Failed            0.0          Poor
Rohid               15           Fox           15.0          Rich

In [202]:
# sort_index(): it is used to sort the index of a dataframe
data.sort_index()

             Hunter_id Hunted_animal  Animal_weight Hunter_status
Hunter_name
Ahmed                6       Elefent         5990.0          Rich
Ahsan                5          Bird           10.0          Poor
Akber               13          Duck           20.0   Middleclass
Ali                  4       buffalo          230.0   MiddleClass
Arslan               9           NaN            NaN          Poor
Hasan               14        Failed            0.0          Poor
Jam                  3           cow          400.0          Poor
Mustafa              7           cow          290.0    MidleClass
Nawaz               12           Got          150.0          Rich
Ram                  1           Cow          250.0   Middleclass
Ram                 11         Tiger         5550.0          Poor
Rohid               15           Fox           15.0          Rich
Sham                 2          Lion         2000.0          Rich
Sita                 8         Geraf         8700.0          Rich
NaN                 10         Gerof            NaN          Rich

In [203]:
#reset_index(): it is used to reset the index of a dataframe
data.reset_index()

   Hunter_name  Hunter_id Hunted_animal  Animal_weight Hunter_status
0          Ram          1           Cow          250.0   Middleclass
1         Sham          2          Lion         2000.0          Rich
2          Jam          3           cow          400.0          Poor
3          Ali          4       buffalo          230.0   MiddleClass
4        Ahsan          5          Bird           10.0          Poor
5        Ahmed          6       Elefent         5990.0          Rich
6      Mustafa          7           cow          290.0    MidleClass
7         Sita          8         Geraf         8700.0          Rich
8       Arslan          9           NaN            NaN          Poor
9          NaN         10         Gerof            NaN          Rich
10         Ram         11         Tiger         5550.0          Poor
11       Nawaz         12           Got          150.0          Rich
12       Akber         13          Duck           20.0   Middleclass
13       Hasan         14        Failed            0.0          Poor
14       Rohid         15           Fox           15.0          Rich

In [204]:
#rename(): this function is used to rename a column
df['Hunter_id'].rename('Hunter_id',inplace=True) # inplace is a parameter used to make the changes perminent in dataframe

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
Name: Hunter_id, dtype: int64

In [205]:
# unique() and nunique(): these  function are used to show the unique vales of a column and no of unique values
df['Hunted_animal'].unique()
df.nunique() # it shows No: of unique values for each column

Hunter_id        15
Hunter_name      13
Hunted_animal    13
Animal_weight    13
Hunter_status     5
dtype: int64

In [206]:
# isnull,notnull,hasnans : these functions are used to show either the valeus in a column of a data frame is null ,non null or nan 
df.isnull() # output will be in boolean form for both
df.notnull()

    Hunter_id  Hunter_name  Hunted_animal  Animal_weight  Hunter_status
0        True         True           True           True           True
1        True         True           True           True           True
2        True         True           True           True           True
3        True         True           True           True           True
4        True         True           True           True           True
5        True         True           True           True           True
6        True         True           True           True           True
7        True         True           True           True           True
8        True         True          False          False           True
9        True        False           True          False           True
10       True         True           True           True           True
11       True         True           True           True           True
12       True         True           True           True           True
13       True         True           True           True           True
14       True         True           True           True           True

In [207]:
#dropna : it removes all na values from series
df.dropna(how='all') # how is a parameter which tell the function how to remove nans , all means if whole row is null any means if row contain any nan
df.dropna(subset='Hunted_animal') # subset is also a parameter which tell from which colum should we remove the nans

    Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
0           1         Ram           Cow          250.0   Middleclass
1           2        Sham          Lion         2000.0          Rich
2           3         Jam           cow          400.0          Poor
3           4         Ali       buffalo          230.0   MiddleClass
4           5       Ahsan          Bird           10.0          Poor
5           6       Ahmed       Elefent         5990.0          Rich
6           7     Mustafa           cow          290.0    MidleClass
7           8        Sita         Geraf         8700.0          Rich
9          10         NaN         Gerof            NaN          Rich
10         11         Ram         Tiger         5550.0          Poor
11         12       Nawaz           Got          150.0          Rich
12         13       Akber          Duck           20.0   Middleclass
13         14       Hasan        Failed            0.0          Poor
14         15       Rohid           Fox           15.0          Rich

In [208]:
# fillna : it fill na values with given vlaue
df.fillna(method='BFILL') # method is  a parameter which tell the function how to fill nan BFill for Bak value fill and FFill for front value fill

C:\Users\Ghulam Mustafa\AppData\Local\Temp\ipykernel_7364\1865471692.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='BFILL') # method is  a parameter which tell the function how to fill nan BFill for Bak value fill and FFill for front value fill

    Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
0           1         Ram           Cow          250.0   Middleclass
1           2        Sham          Lion         2000.0          Rich
2           3         Jam           cow          400.0          Poor
3           4         Ali       buffalo          230.0   MiddleClass
4           5       Ahsan          Bird           10.0          Poor
5           6       Ahmed       Elefent         5990.0          Rich
6           7     Mustafa           cow          290.0    MidleClass
7           8        Sita         Geraf         8700.0          Rich
8           9      Arslan         Gerof         5550.0          Poor
9          10         Ram         Gerof         5550.0          Rich
10         11         Ram         Tiger         5550.0          Poor
11         12       Nawaz           Got          150.0          Rich
12         13       Akber          Duck           20.0   Middleclass
13         14       Hasan        Failed            0.0          Poor
14         15       Rohid           Fox           15.0          Rich

# Group by in pandas 
**Definition :** Group by is used to divide data in groups  on the basis of categorical columns

In [209]:
# synatx : dataframe.groupby('categorical_column')
gb=df.groupby('Hunter_status')
gb['Animal_weight'].sum()

Hunter_status
MiddleClass      230.0
Middleclass      270.0
MidleClass       290.0
Poor            5960.0
Rich           16855.0
Name: Animal_weight, dtype: float64

## Functions of a group by

In [210]:
# len() : len function is used to find the total number of groups in group by
len(gb)

5

In [211]:
# size() : size is used to find the number of items in each group
gb.size()

Hunter_status
MiddleClass    1
Middleclass    2
MidleClass     1
Poor           5
Rich           6
dtype: int64

In [212]:
#first() / last() : these functions are used to find the first and last values of a group by object
gb.first()
gb.last()

               Hunter_id Hunter_name Hunted_animal  Animal_weight
Hunter_status
MiddleClass            4         Ali       buffalo          230.0
Middleclass           13       Akber          Duck           20.0
MidleClass             7     Mustafa           cow          290.0
Poor                  14       Hasan        Failed            0.0
Rich                  15       Rohid           Fox           15.0

In [213]:
# nth() : it is used to find the nth value of group by 
gb.nth(2)

   Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
7          8        Sita         Geraf         8700.0          Rich
8          9      Arslan           NaN            NaN          Poor

In [214]:
# get_groups() : this function is used to get all the values related to a specfic group of group by 
gb.get_group('Poor')

    Hunter_id Hunter_name Hunted_animal  Animal_weight Hunter_status
2           3         Jam           cow          400.0          Poor
4           5       Ahsan          Bird           10.0          Poor
8           9      Arslan           NaN            NaN          Poor
10         11         Ram         Tiger         5550.0          Poor
13         14       Hasan        Failed            0.0          Poor

In [215]:
#group() : this funcction is used to get all the groups of a group by object
gb.groups

{'MiddleClass': [3], 'Middleclass': [0, 12], 'MidleClass': [6], 'Poor': [2, 4, 8, 10, 13], 'Rich': [1, 5, 7, 9, 11, 14]}

In [216]:
# agg() : agg stands for aggregate ,is a special type of fuction of group by which performs more than one aggregate function at a time
# syntax: groupbyobj.agg({ 'colm1':'aggfunction','colm2':'aggfunction'})
gb.agg({'Animal_weight':'mean','Hunter_status':'count'})

               Animal_weight  Hunter_status
Hunter_status
MiddleClass            230.0              1
Middleclass            135.0              2
MidleClass             290.0              1
Poor                  1490.0              5
Rich                  3371.0              6

# Merging of different data frames

In [217]:
df2=pd.DataFrame({'Hunter_id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
                    'Hunter_name':['Ram@gmail.com','Sham@gmail.com','Jam@gmail.com','Ali@gmail.com','Ahsan@gmail.com','Ahmed@gmail.com','Mustafa@gmail.com','Sita@gmail.com','Arslan@gmail.com',np.nan,'Ram@gmail.com','Nawaz@gmail.com','Akber@gmail.com','Hasan@gmail.com','Rohid@gmail.com'],

                    'Hunter_occupation':['Busniss man','Employee','Politision','Teacher','Visitor','Busniss man','Employee','Politision','Politision','Teacher','Busniss man','Busniss man','Visitor','Busniss man','Busniss man']}
            )
df2

    Hunter_id        Hunter_name Hunter_occupation
0           1      Ram@gmail.com       Busniss man
1           2     Sham@gmail.com          Employee
2           3      Jam@gmail.com        Politision
3           4      Ali@gmail.com           Teacher
4           5    Ahsan@gmail.com           Visitor
5           6    Ahmed@gmail.com       Busniss man
6           7  Mustafa@gmail.com          Employee
7           8     Sita@gmail.com        Politision
8           9   Arslan@gmail.com        Politision
9          10                NaN           Teacher
10         11      Ram@gmail.com       Busniss man
11         12    Nawaz@gmail.com       Busniss man
12         13    Akber@gmail.com           Visitor
13         14    Hasan@gmail.com       Busniss man
14         15    Rohid@gmail.com       Busniss man

In [218]:
df.merge(df2,on='Hunter_id' ,how='inner')# at the place of how u can replace left ,right,full

,Hunter_id,Hunter_name_x,Hunted_animal,Animal_weight,Hunter_status,Hunter_name_y,Hunter_occupation
0,1,Ram,Cow,250.0,Middleclass,Ram@gmail.com,Busniss man
1,2,Sham,Lion,2000.0,Rich,Sham@gmail.com,Employee
2,3,Jam,cow,400.0,Poor,Jam@gmail.com,Politision
3,4,Ali,buffalo,230.0,MiddleClass,Ali@gmail.com,Teacher
4,5,Ahsan,Bird,10.0,Poor,Ahsan@gmail.com,Visitor
5,6,Ahmed,Elefent,5990.0,Rich,Ahmed@gmail.com,Busniss man
6,7,Mustafa,cow,290.0,MidleClass,Mustafa@gmail.com,Employee
7,8,Sita,Geraf,8700.0,Rich,Sita@gmail.com,Politision
8,9,Arslan,NaN,NaN,Poor,Arslan@gmail.com,Politision
9,10,NaN,Gerof,NaN,Rich,NaN,Teacher
10,11,Ram,Tiger,5550.0,Poor,Ram@gmail.com,Busniss man
11,12,Nawaz,Got,150.0,Rich,Nawaz@gmail.com,Busniss man
12,13,Akber,Duck,20.0,Middleclass,Akber@gmail.com,Visitor
13,14,Hasan,Failed,0.0,Poor,Hasan@gmail.com,Busniss man
14,15,Rohid,Fox,15.0,Rich,Rohid@gmail.com,Busniss man

# Multiindexing

In [219]:
index=pd.MultiIndex.from_product([['ece','cee','acc','cic'],[2023,2024,2025]])
index

MultiIndex([('ece', 2023),
            ('ece', 2024),
            ('ece', 2025),
            ('cee', 2023),
            ('cee', 2024),
            ('cee', 2025),
            ('acc', 2023),
            ('acc', 2024),
            ('acc', 2025),
            ('cic', 2023),
            ('cic', 2024),
            ('cic', 2025)],
           )

In [220]:
MI=pd.DataFrame({'Score':[1,2,3,4,5,6,7,8,9,10,11,12]},index=index)
MI

          Score
ece 2023      1
    2024      2
    2025      3
cee 2023      4
    2024      5
    2025      6
acc 2023      7
    2024      8
    2025      9
cic 2023     10
    2024     11
    2025     12

### Indexing of a MultiIndex

In [221]:
MI.loc['cic']

      Score
2023     10
2024     11
2025     12

In [222]:
MI.loc[('cic',2025)]

Score    12
Name: (cic, 2025), dtype: int64

# Pivot table in pandas

## Pivot_table in pandas

In [223]:
titanic.pivot_table(index='Pclass',columns='Survived',values='Age',aggfunc='count') # You can  give any aggregate function in aggfunc

Survived    0    1
Pclass
1          64  122
2          90   83
3         270   85

### Pivot function
**Explanation :** pivot function takes simple column data and groups into a  contengency table it takes a unique index ,
and do not have aggfunc function but pivot table has.

In [224]:
titanic.pivot(index='PassengerId',columns='Sex',values='Fare')

Sex          female  male
PassengerId
1               NaN   7.0
2              71.0   NaN
3               8.0   NaN
4              53.0   NaN
5               NaN   8.0
...             ...   ...
887             NaN  13.0
888            30.0   NaN
889            23.0   NaN
890             NaN  30.0
891             NaN   8.0

[891 rows x 2 columns]

# Vectorized Operations in string

In [225]:
# You can perform any vectorized opertion  on strings using .str function ,it enables you to perform operations in string
titanic['Name'].str.title() # first letter of each word is capital remaning lower

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

#### Important vectorized functions

In [226]:
# lower() / upper()
titanic['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [227]:
titanic['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [228]:
# strip() : strip function is used to remove unnessassary spaces from column
titanic['Cabin'].str.strip()

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [3]:
#split('separator',n=No of parts) : split function is used to divide a string in n number of parts on the base of any separator
titanic['Name'].str.split(',')

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [4]:
# replace() : replace function is used to replace any value with given value
titanic['Sex'].str.replace('female','F').str.replace('male','M')

0      M
1      F
2      F
3      F
4      M
      ..
886    M
887    F
888    F
889    M
890    M
Name: Sex, Length: 891, dtype: object

In [231]:
# startswith() / endwith() : these functions are used to get values on the basis of given condition
titanic[titanic['Name'].str.startswith('Robert')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211,B3,S

In [232]:
titanic[titanic['Name'].str.endswith('Henry')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8,NaN,S
159,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,70,NaN,S
209,210,1,1,"Blank, Mr. Henry",male,40.0,0,0,112277,31,A31,C
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7,NaN,S
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8,NaN,S
239,240,0,2,"Hunt, Mr. George Henry",male,33.0,0,0,SCO/W 1585,12,NaN,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0,NaN,S
385,386,0,2,"Davies, Mr. Charles Henry",male,18.0,0,0,S.O.C. 14879,74,NaN,S
411,412,0,3,"Hart, Mr. Henry",male,NaN,0,0,394140,7,NaN,Q
476,477,0,2,"Renouf, Mr. Peter Henry",male,34.0,1,0,31027,21,NaN,S
482,483,0,3,"Rouse, Mr. Richard Henry",male,50.0,0,0,A/5 3594,8,NaN,S
594,595,0,2,"Chapman, Mr. John Henry",male,37.0,1,0,SC/AH 29037,26,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,14,NaN,S
722,723,0,2,"Gillespie, Mr. William Henry",male,34.0,0,0,12233,13,NaN,S

# Vectorized Timestamp

In [233]:
# creating time stamp 
pd.Timestamp('2025/04/22 05:05')

Timestamp('2025-04-22 05:05:00')

In [234]:
pd.Timestamp('2025-04-03 05:05')

Timestamp('2025-04-03 05:05:00')

In [235]:
pd.Timestamp('5th march 2025 05:05')

Timestamp('2025-03-05 05:05:00')

### DatetimeIndex

In [236]:
# it is uesd to store multiple date times 
pd.DatetimeIndex(['2023','2022','2021','2025','2024'])

DatetimeIndex(['2023-01-01', '2022-01-01', '2021-01-01', '2025-01-01',
               '2024-01-01'],
              dtype='datetime64[ns]', freq=None)

In [237]:
## date_range() : it is used to create multiple datetimes in a given range
pd.date_range(start='2025/08/01' ,end='2025/09/01')

DatetimeIndex(['2025-08-01', '2025-08-02', '2025-08-03', '2025-08-04',
               '2025-08-05', '2025-08-06', '2025-08-07', '2025-08-08',
               '2025-08-09', '2025-08-10', '2025-08-11', '2025-08-12',
               '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16',
               '2025-08-17', '2025-08-18', '2025-08-19', '2025-08-20',
               '2025-08-21', '2025-08-22', '2025-08-23', '2025-08-24',
               '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28',
               '2025-08-29', '2025-08-30', '2025-08-31', '2025-09-01'],
              dtype='datetime64[ns]', freq='D')

In [243]:
df2['birth_date']=pd.date_range(start='2000/02/01',end='2000/05/15',freq='W') # in freq u can add 'W' for weekend,'THU' for thursday,'B' for business day

In [239]:
df2

    Hunter_id        Hunter_name Hunter_occupation birth_date
0           1      Ram@gmail.com       Busniss man 2000-02-06
1           2     Sham@gmail.com          Employee 2000-02-13
2           3      Jam@gmail.com        Politision 2000-02-20
3           4      Ali@gmail.com           Teacher 2000-02-27
4           5    Ahsan@gmail.com           Visitor 2000-03-05
5           6    Ahmed@gmail.com       Busniss man 2000-03-12
6           7  Mustafa@gmail.com          Employee 2000-03-19
7           8     Sita@gmail.com        Politision 2000-03-26
8           9   Arslan@gmail.com        Politision 2000-04-02
9          10                NaN           Teacher 2000-04-09
10         11      Ram@gmail.com       Busniss man 2000-04-16
11         12    Nawaz@gmail.com       Busniss man 2000-04-23
12         13    Akber@gmail.com           Visitor 2000-04-30
13         14    Hasan@gmail.com       Busniss man 2000-05-07
14         15    Rohid@gmail.com       Busniss man 2000-05-14

In [240]:
# dot dt is used to access values of a column containing date information

# THE   END  .  .  .  !